### ISSUE TITLE
No dist folder in 0.1.4

### ISSUE THREAD

**Issue by M-Samoht** [lucassaid/react-headless-agenda#1]
No dist folder in 0.1.4 version published to npm

![image](https://github.com/lucassaid/react-headless-agenda/assets/5079574/f3eb6241-2778-451d-a206-6a59438aa3f5)

![image](https://github.com/lucassaid/react-headless-agenda/assets/5079574/43480944-fe2a-45d1-a21d-3bad66fa92fe)

**Comment by lucassaid** [comment]
Sorry, fixed
